package codespecialist.skillapi.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.Set;

@Setter
@Getter // Auto-generate Setter and Getter with Lombok
@NoArgsConstructor
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity(name = "person") // JPA Annotation to map the table to the class
public class Person {
    @Id // ID attribute of the entity
    @GeneratedValue(strategy = GenerationType.AUTO) // IDs are generated by a database sequence
    private Long id;
    private String name; // Name of the Person

    @ManyToMany // Indicates the relation to skills
    @JoinTable(
            name = "person_skills", // Table that maps the relation
            joinColumns = @JoinColumn(name = "person_id"), // The column this entity joins on
            inverseJoinColumns = @JoinColumn(name = "skill_id")) // Inverse join column
    private Set<Skill> skills; // Skills that belong to the specific person
}